/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.7.1.0 (NJsonSchema v9.6.0.0) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming


/** Class representing a weather forecast. */
export interface WeatherForecast {
    /** Date, formatted. */
    dateFormatted?: string | undefined;
    /** Summary string. */
    summary?: string | undefined;
    /** Temperate in C. */
    temperatureC?: number | undefined;
    /** Returns the temperature in F. */
    readonly temperatureF?: number | undefined;
}

export interface UserDto {
    emailAddress?: string | undefined;
    id?: string | undefined;
    role?: UserDtoRole | undefined;
    userName?: string | undefined;
}

export enum UserDtoRole {
    User = <any>"User", 
    Admin = <any>"Admin", 
}